In [5]:
import pandas as pd

In [28]:
data = pd.read_csv("C:\\Users\\bgarg\\Downloads\\student_info.csv")

In [33]:
data.head(99)

   ID      NAME  MARKS  rank  dense_rank  row_num_rank
0   1  SANTHOSH     75     5           5             5
1   2     KIRAN     90     3           3             3
2   3     ARJUN     77     4           4             4
3   4   KARTHIK     97     2           2             2
4   5     RAJEV     65     6           6             6
5   6     GOPAL     65     6           6             7
6   7     TARUN     35     8           7             8
7   8      DIYA     99     1           1             1

In [30]:
data["rank"]=data["MARKS"].rank(ascending=False).astype("int")

In [31]:
data["dense_rank"]=data["MARKS"].rank(method="dense",ascending=False).astype("int")

In [32]:
data["row_num_rank"]=data["MARKS"].rank(method="first",ascending=False).astype("int")

In [97]:
data1 = pd.read_csv("C:\\Users\\bgarg\\Downloads\\student_info1.csv")

In [98]:
data1.head(9)

   ID      NAME   MEDIUM  MARKS
0   1  SANTHOSH  ENGLISH     75
1   2     KIRAN  KANNADA     90
2   3     ARJUN  KANNADA     77
3   4   KARTHIK  ENGLISH     97
4   5     RAJEV  ENGLISH     65
5   6     GOPAL  KANNADA     65
6   7     TARUN  ENGLISH     35
7   8      DIYA  KANNADA     99

In [99]:
data1["row_num"]=data1.sort_values(by="MARKS",ascending=False).groupby("MEDIUM").cumcount()+1

In [100]:
data1=data1.sort_values(by=["MEDIUM","row_num"],ascending=[True,True])

In [101]:
data1.head(99)

   ID      NAME   MEDIUM  MARKS  row_num
3   4   KARTHIK  ENGLISH     97        1
0   1  SANTHOSH  ENGLISH     75        2
4   5     RAJEV  ENGLISH     65        3
6   7     TARUN  ENGLISH     35        4
7   8      DIYA  KANNADA     99        1
1   2     KIRAN  KANNADA     90        2
2   3     ARJUN  KANNADA     77        3
5   6     GOPAL  KANNADA     65        4

In [59]:
data2 = pd.read_csv("C:\\Users\\bgarg\\Downloads\\sales_info.csv")

In [66]:
data2.head(5)

   C_Year  T_Sales  P_Sales        YoY
4    2012    17500      NaN        NaN
5    2013    15000  17500.0 -14.285714
0    2014    25000  15000.0  66.666667
3    2015    12500  25000.0 -50.000000
1    2016    18000  12500.0  44.000000

In [61]:
data2=data2.sort_values(by="C_Year",ascending=True)

In [62]:
data2["P_Sales"]=data2["T_Sales"].shift(1)

In [65]:
data2["YoY"]= (data2["T_Sales"]-data2["P_Sales"])/(data2["P_Sales"])*100

In [81]:
data3 = pd.read_csv("C:\\Users\\bgarg\\Downloads\\sales_info.csv")

In [82]:
data3.head(9)

   C_Year  T_Sales
0    2014    25000
1    2016    18000
2    2017    23500
3    2015    12500
4    2012    17500
5    2013    15000

In [83]:
data3=data3.sort_values(by="C_Year",ascending=True)

In [84]:
data3["F_Sales"]=data3["T_Sales"].shift(-1)

In [85]:
data3.head(9)

   C_Year  T_Sales  F_Sales
4    2012    17500  15000.0
5    2013    15000  25000.0
0    2014    25000  12500.0
3    2015    12500  18000.0
1    2016    18000  23500.0
2    2017    23500      NaN