In [31]:
additionL = lambda a,b : a+b

In [32]:
additionL(5,6)

11

In [33]:
squareL = lambda a : a*a

In [34]:
squareL(5)

25

In [35]:
transactionT = lambda a :  "Gold" if a >2500 else ("Silver" if a>1500  else "Bronze")

In [36]:
transactionT(1501)

'Silver'

In [37]:
import shutil as s
import os
import platform

In [71]:
s.move("C:\\Users\\bgarg\\OneDrive\\Desktop\\src\\in.txt","C:\\Users\\bgarg\\OneDrive\\Desktop\\target")

'C:\\Users\\bgarg\\OneDrive\\Desktop\\target\\in.txt'

In [30]:
s.copy("C:\\Users\\bgarg\\OneDrive\\Desktop\\target\\in.txt","C:\\Users\\bgarg\\OneDrive\\Desktop\\src")

'C:\\Users\\bgarg\\OneDrive\\Desktop\\src\\in.txt'

In [38]:
os.getlogin()

'bgarg'

In [39]:
platform.system()

'Windows'

In [40]:
platform.node()

'LAPTOP-9KBKS8TE'

In [41]:
platform.version()

'10.0.26100'

In [42]:
platform.processor()

'AMD64 Family 23 Model 104 Stepping 1, AuthenticAMD'

In [43]:
platform.python_version()

'3.11.5'

In [44]:
import numpy as np

In [45]:
np.absolute(-9)

9

In [46]:
np.add(5,6)

11

In [47]:
np.subtract(9,2)

7

In [48]:
b = np.array([1,6,9,45])

In [49]:
b

array([ 1,  6,  9, 45])

In [50]:
b = np.array([[1,6,9,45],[6,7,98,34]])

In [51]:
b

array([[ 1,  6,  9, 45],
       [ 6,  7, 98, 34]])

In [52]:
b[1]

array([ 6,  7, 98, 34])

In [53]:
b[0]

array([ 1,  6,  9, 45])

In [54]:
b[0][1]

6

In [55]:
b[1][2]

98

In [56]:
b=np.array([[[89,44],[1,65],[56,98]]])

In [57]:
b

array([[[89, 44],
        [ 1, 65],
        [56, 98]]])

In [58]:
np.sin(90)

0.8939966636005579

In [59]:
np.sin(0)

0.0

In [60]:
import numpy as np
import pandas as pd

In [61]:
data = pd.read_csv("C:\\Users\\bgarg\\Downloads\\Emp1.csv",encoding='latin-1')

In [62]:
data.head()

,EmployeeID,ManagerID,Title,MaritalStatus,Gender,HireDate,Dept,Job Grade
0,1,16,Gustavo Achong,M,M,02-02-2013 00:00,Sales,Admin
1,2,6,Catherine Abel,S,M,31-08-2013 00:00,Sales,Management
2,3,12,Kim Abercrombie,M,M,16-06-2014 00:00,Finance,Admin
3,4,3,Humberto Acevedo,S,M,10-07-2014 00:00,Logistics,Admin
4,5,263,Pilar Ackerman,M,M,16-07-2014 00:00,Human Resource,Admin

In [63]:
data["MaritalStatus"]= np.where(data["MaritalStatus"]=="M","Married","Single")

In [64]:
data.head()

,EmployeeID,ManagerID,Title,MaritalStatus,Gender,HireDate,Dept,Job Grade
0,1,16,Gustavo Achong,Married,M,02-02-2013 00:00,Sales,Admin
1,2,6,Catherine Abel,Single,M,31-08-2013 00:00,Sales,Management
2,3,12,Kim Abercrombie,Married,M,16-06-2014 00:00,Finance,Admin
3,4,3,Humberto Acevedo,Single,M,10-07-2014 00:00,Logistics,Admin
4,5,263,Pilar Ackerman,Married,M,16-07-2014 00:00,Human Resource,Admin

In [78]:
import mysql
import pmysql

ModuleNotFoundError: No module named 'pmysql'

In [79]:
!pip install pmysql

ERROR: Could not find a version that satisfies the requirement pmysql (from versions: none)
ERROR: No matching distribution found for pmysql

In [67]:
import sqlalchemy
!pip install mysql

Requirement already satisfied: mysql in c:\users\bgarg\anaconda3\lib\site-packages (0.0.3)
Requirement already satisfied: mysqlclient in c:\users\bgarg\anaconda3\lib\site-packages (from mysql) (2.2.7)

In [68]:
from sqlalchemy import create_engine

In [69]:
sqlengine = create_engine("mysql://root:admin@localhost/amazon_db")

In [70]:
dbconnection = sqlengine.connect()

OperationalError: (MySQLdb.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [72]:
squares=[]
for i in range(1,11):
    squares.append(i**2)
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [73]:
square = [i**2 for i in range(1,11)]

In [74]:
square

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [75]:
l = [5,66,78,99]

In [76]:
odd_sq = [i**2 for i in l if i%2!=0]

In [77]:
odd_sq

[25, 9801]